/** Six-column reference list (Indian animal pharmaceutical molecules). */
export const MOLECULE_NAMES_COLUMNS: string[][] = [
  [
    'Afoxolaner',
    'Aglepristone',
    'Albendazole',
    'Altrenogest',
    'Amitraz',
    'Amoxicillin',
    'Amprolium',
    'Amprolium',
    'Azithromycin',
    'Bacitracin',
    'Beclotiamine hydrochloride',
    'Bedinvetmab',
    'Bromhexine hydrochloride',
    'Buparvaquone',
    'Buserelin acetate',
  ],
  [
    'Cefalonium dihydrate',
    'Cefquinome',
    'Cefquinome sulphate',
    'Ceftiofur sodium',
    'Cephalexin',
    'Cephapirin benzathine',
    'Cephapirine benzathine',
    'Chlorhexidine gluconate',
    'Clopidol',
    'Cloprostenol sodium',
    'Clorsulon',
    'Closantel',
    'Deltamethrin',
    'Deslorelin acetate',
    'Dicyclomine hydrochloride',
    'Dimetridazole',
    'Diminazene aceturate',
    'Disophenol',
    'Doramectin',
  ],
  [
    'Enrofloxacin',
    'Eprinomectin',
    'Erythromycin Thiocyanate',
    'Fenbendazole',
    'Fipronil',
    'Flunixin meglumine',
    'Fluralaner',
    'Furaltadone',
    'Human chorionic gonadotrophin',
    'Hydrocortisone',
    'Imidocarb dipropionate',
    'Isometamidium Chloride',
    'Ivermectin',
    'Ketoconazole',
    'Levamisole hydrochloride',
    'Lokivetmab',
  ],
  [
    'Marbofloxacin',
    'Meloxicam',
    'Milbemycin oxime',
    'Monensin sodium',
    'Moxidectin',
    'Neomycin',
    'Oclacitinib',
    'Oclacitinib',
    'Orbifloxacin',
    'Oxibendazole',
    'Oxyclozanide',
  ],
  [
    'Paracetamol',
    'Parbendazole',
    'Permethrin',
    'Phenazone',
    'Pheniramine maleate',
    'Pimobendan',
    'Polymyxin B',
    'Praziquantel',
    'Prednisolone',
    'Pregnant mare serum gonadotrophin',
    'Pyrantel embonate',
    'Pyrantel tartrate',
  ],
  [
    'Quinapyramine chloride',
    'Quinapyramine sulphate',
    'Sarolaner',
    'Selamectin',
    'Sulfanilamide',
    'Suramin',
    'Tetracycline hydrochloride',
    'Tetramisole Hydrochloride',
    'Thiophanate',
    'Tiletamine',
    'Tilmicosin phosphate',
    'Toldimfos sodium',
    'Tylosin tartrate',
    'Virginiamycin',
    'Zinc bacitracin',
    'Zolazepam',
  ],
]

export function getMoleculeNamesRows(): string[][] {
  const max = Math.max(...MOLECULE_NAMES_COLUMNS.map((c) => c.length))
  const out: string[][] = []
  for (let i = 0; i < max; i++) {
    out.push(MOLECULE_NAMES_COLUMNS.map((col) => col[i] ?? ''))
  }
  return out
}
