/** Six-column reference list (Indian animal pharmaceutical molecules). */
export const MOLECULE_NAMES_COLUMNS: string[][] = [
  [
    'Afoxolaner',
    'Aglepristone',
    'Albendazole',
    'Altrenogest',
    'Amitraz',
    'Amoxicillin',
    'Amprolium',
    'Azithromycin',
    'Bacitracin',
    'Beclotiamine Hydrochloride',
    'Bedinvetmab',
    'Bromhexine Hydrochloride',
    'Buparvaquone',
    'Buserelin Acetate',
  ],
  [
    'Cefalonium Dihydrate',
    'Cefquinome',
    'Cefquinome Sulphate',
    'Ceftiofur Sodium',
    'Cephalexin',
    'Cephapirin Benzathine',
    'Chlorhexidine Gluconate',
    'Clopidol',
    'Cloprostenol Sodium',
    'Clorsulon',
    'Closantel',
    'Deltamethrin',
    'Deslorelin Acetate',
    'Dicyclomine Hydrochloride',
    'Dimetridazole',
    'Diminazene Aceturate',
    'Disophenol',
    'Doramectin',
  ],
  [
    'Enrofloxacin',
    'Eprinomectin',
    'Erythromycin Thiocyanate',
    'Fenbendazole',
    'Fipronil',
    'Flunixin Meglumine',
    'Fluralaner',
    'Furaltadone',
    'Human Chorionic Gonadotrophin',
    'Hydrocortisone',
    'Imidocarb Dipropionate',
    'Isometamidium Chloride',
    'Ivermectin',
    'Ketoconazole',
    'Levamisole Hydrochloride',
    'Lokivetmab',
    'Levothyroxine',
  ],
  [
    'Marbofloxacin',
    'Meloxicam',
    'Milbemycin Oxime',
    'Monensin Sodium',
    'Moxidectin',
    'Methimazole',
    'Neomycin',
    'Oclacitinib',
    'Orbifloxacin',
    'Oxibendazole',
    'Oxyclozanide',
  ],
  [
    'Paracetamol',
    'Parbendazole',
    'Permethrin',
    'Phenazone',
    'Pheniramine Maleate',
    'Pimobendan',
    'Polymyxin B',
    'Praziquantel',
    'Prednisolone',
    'Pregnant Mare Serum Gonadotrophin',
    'Pyrantel Embonate',
    'Pyrantel Tartrate',
  ],
  [
    'Quinapyramine Chloride',
    'Quinapyramine Sulphate',
    'Sarolaner',
    'Selamectin',
    'Sulfanilamide',
    'Suramin',
    'Tetracycline Hydrochloride',
    'Tetramisole Hydrochloride',
    'Thiophanate',
    'Tiletamine',
    'Tilmicosin Phosphate',
    'Toldimfos Sodium',
    'Tylosin Tartrate',
    'Virginiamycin',
    'Zinc Bacitracin',
    'Zolazepam',
  ],
]

export function getMoleculeNamesRows(): string[][] {
  const max = Math.max(...MOLECULE_NAMES_COLUMNS.map((c) => c.length))
  const out: string[][] = []
  for (let i = 0; i < max; i++) {
    out.push(MOLECULE_NAMES_COLUMNS.map((col) => col[i] ?? ''))
  }
  return out
}
